# Generated by Django 3.0 on 2020-03-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('entry', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=50)),
                ('meal', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=50)),
            ],
        ),
    ]
